version: '2'
services:
  tws:
    build: .
    ports:
      - "4003:4003"
      - "5901:5900"
    volumes:
      - ./ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib/jts.ini:/root/Jts/jts.ini
      - ./.shared/IBController/Logs:/opt/IBController/Logs 
    environment:
      - TZ=${TZ}
      - TWS_MAJOR_VRSN=${TWS_MAJOR_VRSN}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - IBC_INI=${IBC_INI}
      - IBC_PATH=${IBC_PATH}
      - TWS_PATH=${TWS_PATH}
      - TWS_CONFIG_PATH=${TWS_CONFIG_PATH}
      - LOG_PATH=${LOG_PATH}
      - JAVA_PATH=${JAVA_PATH}
      - TRADING_MODE=${TRADING_MODE}
      - TWSUSERID=${TWSUSERID}
      - TWSPASSWORD=${TWSPASSWORD}
      - FIXUSERID=${FIXUSERID}
      - FIXPASSWORD=${FIXPASSWORD}
      - APP=GATEWAY
